/home/tvrtko/Infobip-service/.env/lib/python3.10/site-packages/distributed/client.py:3162: UserWarning: Sending large graph of size 28.27 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
/home/tvrtko/Infobip-service/.env/lib/python3.10/site-packages/distributed/client.py:3162: UserWarning: Sending large graph of size 37.20 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
<Client: 'tcp://127.0.0.1:35137' processes=8 threads=64, memory=251.55 GiB>
Reading raw data...
Raw data read.
Calculating max time...
Max time calculated.
Removing users without history...
Users without history removed.
Preparing data...
Data prepared.
Reading raw data...
Raw data read.
Calculating time threshold...
Time threshold calculated.
Time thresholding...
Time thresholding done.
Removing users without history...
Users without history removed.
Splitting data...
Data split to train/validation.
Preparing data...
Data prepared.
<Client: 'tcp://127.0.0.1:46331' processes=8 threads=64, memory=251.55 GiB>
Traceback (most recent call last):
  File "/home/tvrtko/Infobip-service/infobip_service/preprocessing.py", line 470, in <module>
    calculate_vocab(
  File "/home/tvrtko/Infobip-service/infobip_service/preprocessing.py", line 440, in calculate_vocab
    with open(processed_data_path / f"{column}_vocab.json", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/DefinitionId_vocab.json'
<Client: 'tcp://127.0.0.1:44603' processes=8 threads=64, memory=251.55 GiB>
Traceback (most recent call last):
  File "/home/tvrtko/Infobip-service/infobip_service/preprocessing.py", line 472, in <module>
    calculate_vocab(
  File "/home/tvrtko/Infobip-service/infobip_service/preprocessing.py", line 440, in calculate_vocab
    with open(processed_data_path / f"{column}_vocab.json", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/DefinitionId_vocab.json'
